org: antoniocot
service: api-web-scraping-new

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::316129865556:role/LabRole

plugins:
  - serverless-python-requirements

functions:
  scrape_table:
    handler: handler.scrape_table
    events:
      - http:
          path: scrape/table
          method: get

custom:
  pythonRequirements:
    dockerizePip: true

resources:
  Resources:
    TableWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TableWebScrapping_New
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
