service: api-web-scraping-sismos

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    TABLE_NAME: TablaWebScrapping_New
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:BatchWriteItem"
      Resource: "arn:aws:dynamodb:us-east-1:*:table/TablaWebScrapping_New"

functions:
  scrapeTable:
    handler: handler.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:YOUR_ACCOUNT_ID:layer:chrome-selenium-layer:1
    events:
      - http:
          path: scrape/table
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping_New
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
